mapadoacolhimento/mapa-migrations

migrations/20240227172853_adds_busara_hashes_table/migration.sql, schema.prisma
Esse PR adiciona a tabela `busara_hashes` para facilitar as nossas comunicações com as MSRs sobre a pesquisa da Busara
=> feat: adds busara_hashes table

migrations/20240227204313_adds_multipliers_tables/migration.sql, schema.prisma
Esse PR adiciona as primeiras tabelas do Programa de Multiplicadoras
=> feat: adds multipliers tables

migrations/20240228004113_removes_shift_availability_enum/migration.sql, schema.prisma
Esse PR remove o enum do shift_availability que estava prejudicando a nossa vida D:
=> fix: removes shift_availability enum

migrations/20240320192011_adds_volunteer_segments_table/migration.sql, schema.prisma
Esse PR cria a tabela `volunteer_segments`, que será utilizada para guardar as segmentações de voluntárias.
=> [MAPA-220] feat: adds volunteer_segments table

migrations/20240416192956_adds_status_scheduled_social_worker/migration.sql, schema.prisma
Novo status Assistente Social: Agendado
=> [MAPA-222] add status scheduled_social_worker

migrations/20240417185617_adds_status_expired_social_worker/migration.sql, schema.prisma
Novo status Assistente Social: Expirado
=> [MAPA-222] add status expired_social_worker

migrations/20240516202351_adds_public_services_table/migration.sql, migrations/20240516203312_fixes_service_type_column/migration.sql, schema.prisma
Esse PR adiciona a tabela `public_services` que guardará as informações do Serviços Públicos vindas da base de dados do 180
=> [MAPA-283] feat: adds public_services table

.github/workflows/migrate.yml, migrations/20240701184137_removes_msr_old_tables/migration.sql, migrations/20240701210133_adds_new_msr_tables/migration.sql, migrations/20240701210551_adds_msr_status_enum/migration.sql, migrations/20240702182029_adds_new_msr_columns/migration.sql, migrations/20240702184458_removes_msr_id_relation_with_support_reques/migration.sql, migrations/20240702222426_adds_msr_date_of_birth/migration.sql, migrations/20240702222624_allows_null_date_of_birth/migration.sql, migrations/20240703203744_removes_msr_pii_mask/migration.sql, schema.prisma
Esse PR remove as tabelas antigas de MSRs e adiciona as novas. 
Obs: o enum `MSRStatus` ainda será complementado quando tivermos uma visão mais clara de quais serão os status na jornada da MSR
=> [MAPA-410] feat: adds new MSR tables

migrations/20240813180834_adds_waiting_for_confirmation_support_request_status/migration.sql, migrations/20240813181412_adds_match_type_and_match_stage_to_match_confirmations/migration.sql, migrations/20240813182737_renames_match_confirmation_columns/migration.sql, schema.prisma
Esse PR adiciona alguns fixes necessário para a feature de confirmação do match:
- adiciona o status `waiting_for_confirmation` para o support_request
- adiciona as colunas `match_type` e `match_stage` na tabela `match_confirmations`
=> fix: match confirmations fixes

migrations/20240815194401_fixes_volunteer_condition_length/migration.sql, migrations/20240815195137_fixes_volunteer_status_length/migration.sql, schema.prisma
Esse PR aumenta o length da coluna `condition` na tabela `volunteers`.
=> fix: fixes volunteer condition length

.github/workflows/update-schema.yml, mongodb/schema.prisma, mongodb/seed.mjs, postgres/schema.prisma
=> [MAPA-463] Atulizar o modelo MsrRegisterData

mongodb/schema.prisma
=> [MAPA-462]  update type of externalSupport of table MsrRegisterData

mongodb/schema.prisma, mongodb/seed.mjs
=> [MAPA-686] add field street

postgres/migrations/20241219180839_adds_quality_of_life_survey_tables/migration.sql, postgres/migrations/20241219184941_allows_null_feelings/migration.sql, postgres/schema.prisma
Esse PR adiciona as tabelas que irão armazenar os dados dos Instrumentais de Qualidade de Vida.
=> feat: adds quality of life survey tables

.github/workflows/update-schema.yml
=> [MAPA-709]  fix path  to find schema on repository boas-vindas-chatbot

postgres/migrations/20250127195456_adds_support_evaluation_tables/migration.sql, postgres/schema.prisma
Esse PR adiciona as tabelas dos Instrumentais de Avaliação do Atendimento (MSR)
=> feat: adds support evaluation tables

mongodb/schema.prisma
=> feat(mongodb):add disability field

.github/workflows/update-schema.yml, postgres/migrations/20250408204750_adds_undelivered_to_match_confirmation/migration.sql, postgres/schema.prisma
=> SCRUM-45 (postgres): add undelivered status to match confirmation

.github/workflows/update-schema.yml
=> fix: fix path on boas-vindas-chatbo repository

mongodb/schema.prisma
=> (mongodb) create violenceTime field
